'use client'

import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  X, Bell, CheckCheck, CreditCard,
  Target, Zap, AlertTriangle, MessageSquare, Check,
  Send, Phone,
} from 'lucide-react'
import { toast } from 'sonner'
import { cn, timeAgo } from '@/lib/utils'

type NotifType = 'payment' | 'lead' | 'renewal' | 'message' | 'alert' | 'system'

type Recipient = { name: string; phone: string }

type Notification = {
  id: string
  type: NotifType
  title: string
  body: string
  time: string
  read: boolean
  sendable?: boolean
  recipients?: Recipient[]
  defaultMsg?: string
  autoGenerated?: boolean   // recipients from DB — no add/edit allowed
}

const INITIAL: Notification[] = [
  {
    id: '1', type: 'renewal', read: false, sendable: true, autoGenerated: true,
    title: '5 Memberships Expire Tomorrow',
    body:  'Ananya Singh, Vikram Patel, Arjun Mehta & 2 others expire on June 4th.',
    time:  new Date(Date.now() - 10 * 60000).toISOString(),
    recipients: [
      { name: 'Ananya Singh',  phone: '+91 76543 21098' },
      { name: 'Vikram Patel',  phone: '+91 65432 10987' },
      { name: 'Arjun Mehta',   phone: '+91 43210 98765' },
      { name: 'Priya Sharma',  phone: '+91 98765 43210' },
      { name: 'Rohan Gupta',   phone: '+91 91234 56789' },
    ],
    defaultMsg: 'Namaste {{name}} ji! 🙏\n\nAapki membership kal expire ho rahi hai.\n\nAbhi renew karein!\n💳 UPI: gym@upi\n\nDhanyawad! 🙏',
  },
  {
    id: '2', type: 'lead', read: false, sendable: true,
    title: 'New Lead from WhatsApp',
    body:  'Kavya Reddy enquired about Elite plan. Score: 78.',
    time:  new Date(Date.now() - 22 * 60000).toISOString(),
    recipients: [{ name: 'Kavya Reddy', phone: '+91 54321 09876' }],
    defaultMsg: 'Namaste {{name}} ji! 🙏\n\nThank you for your enquiry.\n\nWould you like to schedule a free trial visit?\n\nReply YES to confirm! ✅',
  },
  {
    id: '3', type: 'payment', read: false, sendable: true,
    title: 'Payment Received',
    body:  'Rahul Kumar paid ₹3,999 for Growth plan via UPI.',
    time:  new Date(Date.now() - 45 * 60000).toISOString(),
    recipients: [{ name: 'Rahul Kumar', phone: '+91 87654 32109' }],
    defaultMsg: 'Namaste {{name}} ji! 🙏\n\nAapka ₹3,999 payment confirm ho gaya hai.\n\nGrowth membership active hai. Gym mein swagat hai! 💪',
  },
  {
    id: '4', type: 'message', read: true, sendable: false,
    title: 'New WhatsApp Message',
    body:  'Priya Sharma: "Haan ji pricing bata do please" — AI is handling.',
    time:  new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: '5', type: 'alert', read: true, sendable: true, autoGenerated: true,
    title: 'Payment Overdue',
    body:  "Vikram Patel's payment of ₹3,999 is overdue by 5 days.",
    time:  new Date(Date.now() - 3 * 3600000).toISOString(),
    recipients: [{ name: 'Vikram Patel', phone: '+91 65432 10987' }],
    defaultMsg: 'Namaste {{name}} ji,\n\nAapka ₹3,999 payment pending hai.\n\n📲 UPI: gym@upi\n\nKripya aaj payment karein.\n\nDhanyawad! 🙏',
  },
  {
    id: '7', type: 'renewal', read: true, sendable: true, autoGenerated: true,
    title: '3 Renewals Due This Week',
    body:  'Vikram Patel, Arjun Mehta & Priya Sharma — expire within 7 days.',
    time:  new Date(Date.now() - 8 * 3600000).toISOString(),
    recipients: [
      { name: 'Vikram Patel', phone: '+91 65432 10987' },
      { name: 'Arjun Mehta',  phone: '+91 43210 98765' },
      { name: 'Priya Sharma', phone: '+91 98765 43210' },
    ],
    defaultMsg: 'Namaste {{name}} ji! 🙏\n\nAapki membership jaldi expire hone wali hai.\n\nAbhi renew karein aur 10% discount payen! 🎉',
  },
  {
    id: '8', type: 'system', read: true, sendable: false,
    title: 'AI Daily Summary',
    body:  'Asha handled 18 conversations · 12 leads qualified · 34% conversion.',
    time:  new Date(Date.now() - 12 * 3600000).toISOString(),
  },
]

const typeConfig: Record<NotifType, { icon: React.ElementType; color: string; bg: string }> = {
  payment: { icon: CreditCard,    color: 'text-green',      bg: 'bg-green/10 border-green/20'           },
  lead:    { icon: Target,        color: 'text-violet-400', bg: 'bg-violet-500/10 border-violet-500/20' },
  renewal: { icon: AlertTriangle, color: 'text-orange',     bg: 'bg-orange/10 border-orange/20'         },
  message: { icon: MessageSquare, color: 'text-blue-soft',  bg: 'bg-blue/10 border-blue/20'             },
  alert:   { icon: AlertTriangle, color: 'text-red',        bg: 'bg-red/10 border-red/20'               },
  system:  { icon: Zap,           color: 'text-text-muted', bg: 'bg-surface2 border-border'             },
}

// ── Send Widget — clean, no duplication ──────────────
function SendWidget({ notif }: { notif: Notification }) {
  const [sending, setSending] = useState(false)
  const [sent, setSent]       = useState(false)
  const count = notif.recipients?.length || 0

  async function handleSend() {
    setSending(true)
    await new Promise(r => setTimeout(r, 800))
    setSending(false); setSent(true)
    toast.success(`WhatsApp reminder sent to ${count} recipient${count !== 1 ? 's' : ''}`)
    setTimeout(() => setSent(false), 3000)
  }

  return (
    <div className="mt-2" onClick={e => e.stopPropagation()}>
      {/* Recipients preview */}
      {notif.recipients && notif.recipients.length > 0 && (
        <div className="flex flex-wrap gap-1 mb-2">
          {notif.recipients.map(r => (
            <span key={r.phone} className="text-[10px] bg-surface2 border border-border text-text-muted px-1.5 py-0.5 rounded flex items-center gap-1">
              <Phone className="w-2 h-2" />{r.name}
            </span>
          ))}
        </div>
      )}

      <button onClick={handleSend} disabled={sending || sent}
        className={cn('flex items-center gap-1.5 text-[11px] font-medium px-2.5 py-1.5 rounded-lg border transition-all',
          sent    ? 'bg-green/10 border-green/25 text-green'
          : sending ? 'bg-surface2 border-border text-text-muted'
          : 'bg-surface2 border-border text-text-muted hover:border-green/25 hover:text-green hover:bg-green/5')}>
        {sent ? <><Check className="w-3 h-3" />Sent!</>
          : sending ? <><motion.div animate={{ rotate: 360 }} transition={{ duration: 0.8, repeat: Infinity, ease: 'linear' }}
              className="w-3 h-3 border-2 border-text-muted/30 border-t-text-muted rounded-full" />Sending...</>
          : <><Send className="w-3 h-3" />Send to {count}</>}
      </button>
    </div>
  )
}

// ── Main panel ────────────────────────────────────────
interface Props {
  open: boolean
  onClose: () => void
  onUnreadChange: (count: number) => void
}

export function NotificationsPanel({ open, onClose, onUnreadChange }: Props) {
  const [notifs, setNotifs] = useState<Notification[]>(INITIAL)
  const [filter, setFilter] = useState<'all' | 'unread'>('all')

  const unread  = notifs.filter(n => !n.read).length
  const visible = filter === 'unread' ? notifs.filter(n => !n.read) : notifs

  // Sync unread count to parent AFTER render — avoids setState-during-render error
  useEffect(() => {
    onUnreadChange(unread)
  }, [unread])

  function markRead(id: string) {
    setNotifs(prev => prev.map(n => n.id === id ? { ...n, read: true } : n))
  }

  function markAllRead() {
    setNotifs(prev => prev.map(n => ({ ...n, read: true })))
  }

  function deleteNotif(id: string) {
    setNotifs(prev => prev.filter(n => n.id !== id))
  }

  return (
    <AnimatePresence>
      {open && (
        <>
          <motion.div key="bd"
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            transition={{ duration: 0.15 }}
            className="fixed inset-0 bg-black/40 z-40" onClick={onClose} />

          <motion.div key="panel"
            initial={{ x: '100%', opacity: 0 }} animate={{ x: 0, opacity: 1 }}
            exit={{ x: '100%', opacity: 0 }}
            transition={{ type: 'spring', stiffness: 300, damping: 30 }}
            className="fixed right-0 top-0 h-full w-full max-w-sm bg-surface border-l border-border shadow-2xl z-50 flex flex-col">

            {/* Header */}
            <div className="flex items-center justify-between px-5 py-4 border-b border-border flex-shrink-0">
              <div className="flex items-center gap-2.5">
                <Bell className="w-4 h-4 text-text-muted" />
                <h2 className="text-sm font-semibold text-text-primary">Notifications</h2>
                {unread > 0 && (
                  <span className="bg-blue text-white text-[10px] font-bold px-1.5 py-0.5 rounded-full min-w-[18px] text-center">
                    {unread}
                  </span>
                )}
              </div>
              <div className="flex items-center gap-1">
                {unread > 0 && (
                  <button onClick={markAllRead}
                    className="flex items-center gap-1 text-xs text-text-muted hover:text-blue-soft px-2 py-1 rounded-lg hover:bg-surface2 transition-colors">
                    <CheckCheck className="w-3.5 h-3.5" /> Mark all read
                  </button>
                )}
                <button onClick={onClose}
                  className="w-7 h-7 flex items-center justify-center rounded-lg hover:bg-surface2 transition-colors ml-1">
                  <X className="w-4 h-4 text-text-muted" />
                </button>
              </div>
            </div>

            {/* Filter tabs */}
            <div className="flex border-b border-border flex-shrink-0">
              {(['all', 'unread'] as const).map(f => (
                <button key={f} onClick={() => setFilter(f)}
                  className={cn('flex-1 py-2.5 text-xs font-medium capitalize transition-colors border-b-2',
                    filter === f ? 'border-blue text-blue-soft' : 'border-transparent text-text-muted hover:text-text-secondary')}>
                  {f === 'all' ? `All (${notifs.length})` : `Unread (${unread})`}
                </button>
              ))}
            </div>

            {/* List */}
            <div className="flex-1 overflow-y-auto">
              {visible.length === 0 ? (
                <div className="flex flex-col items-center justify-center h-full gap-3 text-text-muted">
                  <Bell className="w-10 h-10 opacity-20" />
                  <p className="text-sm">{filter === 'unread' ? 'No unread notifications' : 'No notifications'}</p>
                </div>
              ) : (
                <AnimatePresence initial={false}>
                  {visible.map(n => {
                    const cfg  = typeConfig[n.type]
                    const Icon = cfg.icon
                    return (
                      <motion.div key={n.id}
                        initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, x: 20, height: 0 }} transition={{ duration: 0.2 }}
                        onClick={() => markRead(n.id)}
                        className={cn('px-4 py-3.5 border-b border-border/50 cursor-pointer hover:bg-surface2 transition-colors group relative',
                          !n.read && 'bg-blue/[0.03]')}>

                        {!n.read && <div className="absolute left-1.5 top-5 w-1.5 h-1.5 bg-blue rounded-full" />}

                        <div className="flex items-start gap-3">
                          <div className={cn('w-8 h-8 rounded-xl flex items-center justify-center border flex-shrink-0 mt-0.5', cfg.bg)}>
                            <Icon className={cn('w-3.5 h-3.5', cfg.color)} />
                          </div>

                          <div className="flex-1 min-w-0">
                            <div className="flex items-start justify-between gap-2">
                              <p className={cn('text-xs font-semibold', !n.read ? 'text-text-primary' : 'text-text-secondary')}>
                                {n.title}
                              </p>
                              <div className="flex items-center gap-1 flex-shrink-0">
                                <span className="text-[10px] text-text-muted">{timeAgo(n.time)}</span>
                                <button onClick={e => { e.stopPropagation(); deleteNotif(n.id) }}
                                  className="opacity-0 group-hover:opacity-100 transition-opacity w-4 h-4 flex items-center justify-center text-text-muted hover:text-red">
                                  <X className="w-3 h-3" />
                                </button>
                              </div>
                            </div>
                            <p className="text-xs text-text-muted mt-0.5 leading-relaxed">{n.body}</p>

                            {n.sendable && n.recipients && (
                              <SendWidget notif={n} />
                            )}
                          </div>
                        </div>
                      </motion.div>
                    )
                  })}
                </AnimatePresence>
              )}
            </div>

            <div className="px-5 py-3 border-t border-border flex-shrink-0">
              <p className="text-xs text-text-muted text-center">{notifs.length} notifications · {unread} unread</p>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  )
}
